### PR TITLE
fix: returns "not supported" when supported version is "preview"

### PR DESCRIPTION
**Pull request by camertron**
I ran into an issue running stylelint in primer/view_components:

```
TypeError: Invalid comparator: preview
    at Comparator.parse (/Users/camertron/workspace/primer/view_components/node_modules/semver/classes/comparator.js:39:13)
    at new Comparator (/Users/camertron/workspace/primer/view_components/node_modules/semver/classes/comparator.js:23:10)
    at /Users/camertron/workspace/primer/view_components/node_modules/semver/classes/range.js:152:47
    at Array.map (<anonymous>)
    at Range.parseRange (/Users/camertron/workspace/primer/view_components/node_modules/semver/classes/range.js:152:35)
    at /Users/camertron/workspace/primer/view_components/node_modules/semver/classes/range.js:40:22
    at Array.map (<anonymous>)
    at new Range (/Users/camertron/workspace/primer/view_components/node_modules/semver/classes/range.js:40:8)
    at Object.minVersion (/Users/camertron/workspace/primer/view_components/node_modules/semver/ranges/min-version.js:6:11)
    at isSupported (/Users/camertron/workspace/primer/view_components/node_modules/stylelint-browser-compat/lib/is_supported.js:37:41)
```

It looks like the MDN browser data contains "invalid" (at least, according to semver) versions like "preview". This PR checks for version validity before attempting to call `minVersion`.

### CODE REVIEW

**Comment by jonrohan** [comment]
For what it's worth,

`scrollbar-width: thin;` is what's causing this error, I guess it's possibly looking up safari versions and finding `preview` https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#browser_compatibility

**Comment by jonrohan** [comment]
@3846masa We're still seeing this with other preview features. Any chance you could add to the next release?

**Comment by 3846masa** [comment]
Sorry for late response.
I'll check your PR and the code that fixed your issue will be released in few days.

**Comment by 3846masa** [comment]
`semver.valid()` validates semver strictly, so almost values ​​in mdn/compat-data are marked as invalid.

This issue only occurs when version is "preview", so I've decided to mark the target as "unsupported in all versions" when version is "preview".

This PR will be released v1.0.0-beta.139.

**Pull request merged**
